### ISSUE TITLE
tagKeyWords functionality 

### ISSUE THREAD

**Issue by kzisme** [kzisme/HnTagger#2]
Just testing some stuff and for some reason "web" was append to a title that didn't contain the word.

<img width="1279" alt="screen shot 2016-01-12 at 23 11 05" src="https://cloud.githubusercontent.com/assets/3493562/12284874/f00219a4-b981-11e5-9330-057a33671205.png">

**Comment by paddatrapper** [comment]
It is being picked up from the URL: http://**web**demo.myscript.com/

**Comment by kzisme** [comment]
Ah I'm silly :P
